import "./index.less";
import "ant-design-vue/es/form/style/index.css";
import $ from "jquery";
import { xU as mylodash } from "./ventoseUtils.js";
import { Cpt_UI_locale, State_UI } from "./State_UI";
import dayjs from "dayjs";
import { defCol, defColActions, defColActionsBtnlist, defDataGridOption, defPagination, getPaginationPageSize, setDataGridInfo, setPagination } from "./xDataGrid/common";
import { antColKey, defItem, vModel } from "./xForm/common.jsx";
import { AllWasWell, EVENT_TYPE, validateForm } from "./tools/validate.js";
import { setCSSVariables, setDocumentTitle } from "./tools/dom.jsx";
import { lStorage } from "./tools/storage.js";
import { pickValueFrom, resetValueOf } from "./tools/form.jsx";
import { UI } from "./UI";
export { UI as UI };
export { dayjs as moment };
export { dayjs as dayjs };
export { mylodash as _ };
export { $ as $ };
export { defPagination as defPagination };
export { defCol as defCol };
export { defColActions as defColActions };
export { defColActionsBtnlist as defColActionsBtnlist };
export { defDataGridOption as defDataGridOption };
export { setDataGridInfo as setDataGridInfo };
export { State_UI as State_UI };
export { Cpt_UI_locale as Cpt_UI_locale };
export { lStorage as lStorage };
export { EVENT_TYPE as EVENT_TYPE };
export { setPagination as setPagination };
export { getPaginationPageSize as getPaginationPageSize };
export { validateForm as validateForm };
export { AllWasWell as AllWasWell };
export { setDocumentTitle as setDocumentTitle };
export { setCSSVariables as setCSSVariables };
export { defItem as defItem };
export { vModel as vModel };
export { antColKey as antColKey };
export { pickValueFrom as pickValueFrom };
export { resetValueOf as resetValueOf };
export declare const VentoseUIWithInstall: {
    install: (app: any, options: any) => void;
};
